[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "npm ci",
  "npm run build",
  "cp -r attached_assets dist/"
]

[start]
cmd = "node dist/index.js"