[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --only=production"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r attached_assets dist/"
]

[start]
cmd = "node dist/index.js"