[variables]
NODE_ENV = "production"
NODE_VERSION = "20"

[phases.build]
cmds = [
  "npm ci --verbose",
  "npm run build",
  "mkdir -p dist/attached_assets",
  "cp -r attached_assets/* dist/attached_assets/"
]

[phases.start]
cmd = "node dist/index.js"